// File auto generated by scanning "components.hpp" by struct_parser.exe, from Custom_Preproceccors
#pragma once
#include <memory>
#include "memory.hpp"
#include "components.hpp"

namespace myecs {

template <typename component>
void delete_component(std::unique_ptr<component>& pointer, std::size_t& index);
 
template <>
void delete_component<comp::position>(std::unique_ptr<comp::position>& pointer, std::size_t& index);
 
template <>
void delete_component<comp::rectangle>(std::unique_ptr<comp::rectangle>& pointer, std::size_t& index);
 
template <>
void delete_component<comp::circle>(std::unique_ptr<comp::circle>& pointer, std::size_t& index);
 
template <>
void delete_component<comp::color>(std::unique_ptr<comp::color>& pointer, std::size_t& index);
 
template <>
void delete_component<comp::segment>(std::unique_ptr<comp::segment>& pointer, std::size_t& index);
 
template <>
void delete_component<comp::physics>(std::unique_ptr<comp::physics>& pointer, std::size_t& index);
}
