// File auto generated by scanning "components.hpp" by struct_parser.exe, from Custom_Preproceccors
#include <memory>
#include "memory.hpp"
#include "components.hpp"
#include "generated_components_create.hpp"


template <typename component>
void myecs::create_component(std::unique_ptr<component>& pointer) {}
 
template <>
void myecs::create_component<comp::position>(std::unique_ptr<comp::position>& pointer){
  pointer->x.emplace_back();
  pointer->y.emplace_back();
}
 
template <>
void myecs::create_component<comp::rectangle>(std::unique_ptr<comp::rectangle>& pointer){
  pointer->width.emplace_back();
  pointer->height.emplace_back();
  pointer->shape.emplace_back();
}
 
template <>
void myecs::create_component<comp::circle>(std::unique_ptr<comp::circle>& pointer){
  pointer->radius.emplace_back();
  pointer->shape.emplace_back();
}
 
template <>
void myecs::create_component<comp::color>(std::unique_ptr<comp::color>& pointer){
  pointer->value.emplace_back();
}
 
template <>
void myecs::create_component<comp::segment>(std::unique_ptr<comp::segment>& pointer){
  pointer->obj.emplace_back();
}

