// File auto generated by scanning "components.hpp" by struct_parser.exe, from Custom_Preproceccors
#pragma once
#include <memory>
#include "memory.hpp"
#include "components.hpp"

namespace myecs {

template <typename component>
void create_component(std::unique_ptr<component>& pointer) {}
 
template <>
void create_component<comp::position>(std::unique_ptr<comp::position>& pointer){
  pointer->x.emplace_back();
  pointer->y.emplace_back();
}
 
template <>
void create_component<comp::position_grid>(std::unique_ptr<comp::position_grid>& pointer){
  pointer->x.emplace_back();
  pointer->y.emplace_back();
}
 
template <>
void create_component<comp::rectangle>(std::unique_ptr<comp::rectangle>& pointer){
  pointer->width.emplace_back();
  pointer->height.emplace_back();
}
 
template <>
void create_component<comp::circle>(std::unique_ptr<comp::circle>& pointer){
  pointer->radius.emplace_back();
}
 
template <>
void create_component<comp::color>(std::unique_ptr<comp::color>& pointer){
  pointer->r.emplace_back();
  pointer->g.emplace_back();
  pointer->b.emplace_back();
}
 
template <>
void create_component<comp::physics>(std::unique_ptr<comp::physics>& pointer){
  pointer->speed.emplace_back();
  pointer->direction.emplace_back();
}
 
template <>
void create_component<comp::speed_handler>(std::unique_ptr<comp::speed_handler>& pointer){
  pointer->move_interval.emplace_back();
  pointer->time_accumulator.emplace_back();
  pointer->dt.emplace_back();
}
 
template <>
void create_component<comp::magnitude>(std::unique_ptr<comp::magnitude>& pointer){
  pointer->size.emplace_back();
}

}
