// File auto generated by scanning "components.hpp" by struct_parser.exe, from Custom_Preproceccors
#include <memory>
#include "memory.hpp"
#include "components.hpp"
#include "generated_components_delete.hpp"


template <typename component>
void myecs::delete_component(std::unique_ptr<component>& pointer, std::size_t& index) {// can handle exceptions}
 
template <>
void myecs::delete_component<comp::position>(std::unique_ptr<comp::position>& pointer, std::size_t& index){
  pointer->x[index] = pointer->x[pointer->x.size() - 1];
  pointer->x.pop_back();
  pointer->y[index] = pointer->y[pointer->y.size() - 1];
  pointer->y.pop_back();
}
 
template <>
void myecs::delete_component<comp::rectangle>(std::unique_ptr<comp::rectangle>& pointer, std::size_t& index){
  pointer->width[index] = pointer->width[pointer->width.size() - 1];
  pointer->width.pop_back();
  pointer->height[index] = pointer->height[pointer->height.size() - 1];
  pointer->height.pop_back();
  pointer->shape[index] = pointer->shape[pointer->shape.size() - 1];
  pointer->shape.pop_back();
}
 
template <>
void myecs::delete_component<comp::circle>(std::unique_ptr<comp::circle>& pointer, std::size_t& index){
  pointer->radius[index] = pointer->radius[pointer->radius.size() - 1];
  pointer->radius.pop_back();
  pointer->shape[index] = pointer->shape[pointer->shape.size() - 1];
  pointer->shape.pop_back();
}
 
template <>
void myecs::delete_component<comp::color>(std::unique_ptr<comp::color>& pointer, std::size_t& index){
  pointer->value[index] = pointer->value[pointer->value.size() - 1];
  pointer->value.pop_back();
}
 
template <>
void myecs::delete_component<comp::segment>(std::unique_ptr<comp::segment>& pointer, std::size_t& index){
  pointer->obj[index] = pointer->obj[pointer->obj.size() - 1];
  pointer->obj.pop_back();
}

