// File auto generated by scanning "components.hpp" by struct_parser.exe, from Custom_Preproceccors // header file
#pragma once
#include <memory>
#include "memory.hpp"
#include "components.hpp"

namespace myecs {

template <typename component>
void create_component(std::unique_ptr<component>& pointer);
 
template <>
void create_component<comp::position>(std::unique_ptr<comp::position>& pointer);
 
template <>
void create_component<comp::rectangle>(std::unique_ptr<comp::rectangle>& pointer);
 
template <>
void create_component<comp::circle>(std::unique_ptr<comp::circle>& pointer);
 
template <>
void create_component<comp::color>(std::unique_ptr<comp::color>& pointer);
 
template <>
void create_component<comp::segment>(std::unique_ptr<comp::segment>& pointer);
 
template <>
void create_component<comp::physics>(std::unique_ptr<comp::physics>& pointer);
}
